// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HideOverlay() {
  return window['go']['main']['App']['HideOverlay']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowOverlay() {
  return window['go']['main']['App']['ShowOverlay']();
}

export function ToggleOverlay() {
  return window['go']['main']['App']['ToggleOverlay']();
}
