// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyAndFlash(arg1:string,arg2:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function Greet(arg1:string):Promise<string>;

export function HideOverlay():Promise<void>;

export function IsVisible():Promise<boolean>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function ShowOverlay():Promise<void>;

export function ToggleOverlay():Promise<void>;
