name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        cd ..
    
    - name: Build app
      run: wails build -platform darwin/universal -clean
    
    - name: Create DMG (Optional)
      run: |
        # Create a DMG file for easier distribution
        mkdir -p dist
        cp -r build/bin/Copyman.app dist/
        hdiutil create -volname "Copyman" -srcfolder dist -ov -format UDZO Copyman-darwin-universal.dmg
    
    - name: Create ZIP
      run: |
        cd build/bin
        zip -r ../../Copyman-darwin-universal.zip Copyman.app
        cd ../..
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Copyman-darwin-universal.zip
          Copyman-darwin-universal.dmg
        name: Copyman ${{ github.ref_name }}
        body: |
          ## What's New in ${{ github.ref_name }}
          
          ### Installation
          1. Download `Copyman-darwin-universal.zip`
          2. Unzip and drag `Copyman.app` to your Applications folder
          3. Right-click and select "Open" for first launch
          4. Grant accessibility permissions in System Preferences
          
          ### Usage
          - `Ctrl+Shift+Space` to toggle overlay
          - `Ctrl+Shift+1-9` for quick copy
          
          **Full changelog**: https://github.com/${{ github.repository }}/compare/v1.0.0...${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}